apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kafka.fullname" . }}-secret
  namespace: {{ .Release.Namespace | quote }}
  labels: 
    app: {{ include "kafka.fullname" . }}-secret
type: Opaque
data:
  kraft-cluster-id: "RXJ4eVl5aTh3eFFvMEtkSVVHRGhiMA=="