apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}-headless
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: tcp-interbroker
      port: {{ .Values.kafka.service.ports.interbroker }}
      protocol: TCP
      targetPort: interbroker
    - name: tcp-client
      port: {{ .Values.kafka.service.ports.client }}
      protocol: TCP
      targetPort: client
    - name: tcp-controller
      protocol: TCP
      port: {{ .Values.kafka.service.ports.controller }}
      targetPort: controller
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}