apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: tcp-client
      port: {{ .Values.kafka.service.ports.client }}
      protocol: TCP
      targetPort: client
      nodePort: null
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}