apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.minio.service.type }}
  ports:
    - port: {{ .Values.minio.service.ports.minioApi }}
      targetPort: minio-api
      protocol: TCP
      name: minio-api
      nodePort: null
    - port: {{ .Values.minio.service.ports.minioConsole }}
      targetPort: minio-console
      protocol: TCP
      name: minio-console
      nodePort: null
  selector:
    {{- include "minio.selectorLabels" . | nindent 4 }}
