apiVersion: v1
kind: Service
metadata:
  name: {{ include "crash.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "crash.labels" . | nindent 4 }}
spec:
  type: {{ .Values.crash.service.type }}
  ports:
    - port: {{ .Values.crash.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "crash.selectorLabels" . | nindent 4 }}
