apiVersion: v1
kind: Service
metadata:
  name: {{ include "zookeeper.fullname" . }}-headless
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "zookeeper.labels" . | nindent 4 }}
  annotations: 
    {{- include "zookeeper.annotations" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    {{- if not .Values.zookeeper.service.disableBaseClientPort }}
    - name: tcp-client
      port: {{ .Values.zookeeper.service.ports.client }}
      targetPort: client
    {{- end }}
    - name: tcp-follower
      port: {{ .Values.zookeeper.service.ports.follower }}
      targetPort: follower
    - name: tcp-election
      port: {{ .Values.zookeeper.service.ports.election }}
      targetPort: election
  selector: 
    {{- include "zookeeper.selectorLabels" . | nindent 4 }}
