{{- /*
Copyright Broadcom, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "zookeeper.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "zookeeper.labels" . | nindent 4 }}
  annotations: 
    {{- include "zookeeper.annotations" . | nindent 4 }}
spec:
  type: {{ .Values.zookeeper.service.type }}
  ports:
    - name: tcp-client
      port: {{ .Values.zookeeper.service.ports.client }}
      targetPort: client
      nodePort: null
    - name: tcp-follower
      port: {{ .Values.zookeeper.service.ports.follower }}
      targetPort: follower
    - name: tcp-election
      port: {{ .Values.zookeeper.service.ports.election }}
      targetPort: election
  selector: 
    {{- include "zookeeper.selectorLabels" . | nindent 4 }}