apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio.fullname" . }}-headless
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: minio-api
      port: {{ .Values.minio.service.ports.minioApi }}
      targetPort: minio-api
    - name: minio-console
      port: {{ .Values.minio.service.ports.minioConsole }}
      targetPort: minio-console
  selector:
    {{- include "minio.selectorLabels" . | nindent 4 }}