[sync_reader]
cluster = false
address = "192.168.31.171:6379"
username = ""
password = "beap123"
tls = false
sync_rdb = true
sync_aof = true
prefer_replica = false
try_diskless = false

[redis_writer]
cluster = false
address = "192.168.31.179:6379"
username = ""
password = "beap123"
tls = false
off_reply = false

[filter]
allow_keys = []
allow_key_prefix = []
allow_key_suffix = []
allow_key_regex = []
block_keys = []
block_key_prefix = []
block_key_suffix = []
block_key_regex = []
allow_db = []
block_db = []
allow_command = []
block_command = []
allow_command_group = []
block_command_group = []
function = ""

[advanced]
dir = "data"
ncpu = 0
pprof_port = 0
status_port = 0
log_file = "shake.log"
log_level = "info"
log_interval = 5
log_rotation = true
log_max_size = 512
log_max_age = 7
log_max_backups = 3
log_compress = true
rdb_restore_command_behavior = "panic"
pipeline_count_limit = 1024
target_redis_client_max_querybuf_len = 1073741824
target_redis_proto_max_bulk_len = 512000000
aws_psync = ""
empty_db_before_sync = false

[module]
target_mbbloom_version = 20603
