apiVersion: v1
kind: Service
metadata:
  namespace: app
  name: redis-cluster
spec:
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
    name: client
  - port: 16379
    targetPort: 16379
    name: gossip
  selector:
    app: redis-cluster

--- 

apiVersion: v1
kind: Service
metadata:
  namespace: app
  name: redis-cli
spec:
  clusterIP: None
  # type: NodePort
  ports:
  - port: 6379
    targetPort: 6379
    name: client
  - port: 16379
    targetPort: 16379
    name: gossip
  selector:
    app: redis-cluster
    #app: redis-single
