apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: app
  name: redis-cluster
spec:
  serviceName: redis-cluster
  replicas: 10
  selector:
    matchLabels:
      app: redis-cluster
  template:
    metadata:
      labels:
        app: redis-cluster
    spec:
      containers:
      - name: redis
        image: 10.17.148.19/app/redis:6.2.7
        ports:
        - containerPort: 6379
          name: client
        - containerPort: 16379
          name: gossip
        command:  ["/etc/redis/update.sh", "redis-server", "/etc/redis/redis.conf", "--cluster-announce-ip $(POD_IP)"]
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: conf
          mountPath: /etc/redis/
          readOnly: false
        - name: data
          mountPath: /data
          readOnly: false
      volumes:
      - name: conf
        configMap:
          name: redis-cluster
          defaultMode: 0755
  volumeClaimTemplates:
  - metadata:
      name: data
      #annotations:
      #  volume.beta.kubernetes.io/storage-class: "redis-nfs-storage"
    spec:
      storageClassName: ceph-rbd
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 200Gi
