apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-data
  namespace: app
  labels:
    component: elasticsearch
    role: data
    app: elasticsearch-data
spec:
  ports:
  - port: 9300
    name: transport
  clusterIP: None
  selector:
    component: elasticsearch
    role: data
    app: elasticsearch-data
