apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-discovery
  namespace: app
  labels:
    component: elasticsearch
    role: master
    app: elasticsearch-master
spec:
  selector:
    component: elasticsearch
    role: master
    app: elasticsearch-master
  ports:
  - name: transport
    port: 9300
    protocol: TCP
  - name: http
    port: 9200
    protocol: TCP
