apiVersion: v1
kind: ConfigMap
metadata:
 name: es-conf
 namespace: app
data:
  log4j2.properties: |-
    status = error
    appender.console.type = Console
    appender.console.name = console
    appender.console.layout.type = PatternLayout
    appender.console.layout.pattern =     [%d{ISO8601}][%-5p][%-25c{1.}] %marker%m%n
    
    rootLogger.level = info
    rootLogger.appenderRef.console.ref = console
    
  elasticsearch.yml: |-
    cluster:
      name: ${CLUSTER_NAME}
    
    node:
      master: ${NODE_MASTER}
      data: ${NODE_DATA}
      name: ${NODE_NAME}
      ingest: ${NODE_INGEST}
      max_local_storage_nodes: ${MAX_LOCAL_STORAGE_NODES}
    
    network.host: ${NETWORK_HOST}
    
    path:
      data: /usr/share/elasticsearch/data
      logs: /usr/share/elasticsearch/logs
    
    bootstrap:
      memory_lock: ${MEMORY_LOCK}
    
    http:
      enabled: ${HTTP_ENABLE}
      compression: true
      cors:
        enabled: ${HTTP_CORS_ENABLE}
        allow-origin: ${HTTP_CORS_ALLOW_ORIGIN}
    
    discovery:
      zen:
        ping.unicast.hosts: ${DISCOVERY_SERVICE}
        minimum_master_nodes: ${NUMBER_OF_MASTERS}

    xpack:
      ml:
        enabled: false

  kibana.yml: |-
    server.port: 5601
    server.host: '0.0.0.0'
    elasticsearch.url: 'http://elasticsearch:9200'
    kibana.index: ".kibana"
    #xpack.security.enabled: false
    #elasticsearch.username: "admin"
    #elasticsearch.password: "123456"
    #searchguard.auth.type: "basicauth"
    #searchguard.cookie.secure: false
    xpack.monitoring.enabled: false
    xpack.graph.enabled: false
    xpack.ml.enabled: false
    xpack.watcher.enabled: false
    xpack.security.enabled: false
