# This rule is not used by the project nginx itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to web.example.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/managed-by: kustomize
  name: nginxapp-viewer-role
rules:
- apiGroups:
  - web.example.com
  resources:
  - nginxapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - web.example.com
  resources:
  - nginxapps/status
  verbs:
  - get
