# This rule is not used by the project nginx itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over web.example.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/managed-by: kustomize
  name: nginxapp-admin-role
rules:
- apiGroups:
  - web.example.com
  resources:
  - nginxapps
  verbs:
  - '*'
- apiGroups:
  - web.example.com
  resources:
  - nginxapps/status
  verbs:
  - get
