---
# tags: deploy_minio

- name: check docker.pid
  stat: 
    path: "/run/docker.pid"
  register: dockerpid_output
  
- name: check users
  stat: 
    path: "/home/{{ admin_user }}/app"
  register: users_output

# - name: 输出users
#   debug:
#     msg: "{{ users_output }}"

- import_tasks: createUser.yml
  when: users_output.stat.exists != True
- import_tasks: dockerEnv.yml
  when: dockerpid_output.stat.exists != True
  
- name: copy minio
  copy:
    src: "server/minio"
    dest: "/home/{{ admin_user }}/server/"
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    force: yes
    mode: 0755

- name: 创建部署所需要的目录 
  file:
    path: "/home/{{ admin_user }}/server/minio/{{ item }}"
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    force: yes
    mode: 0755
    recurse: yes
    state: directory
  with_items:
    - bin
    - backups
    - config
    - images
    - log
    - data
    - tmp

- name: chmod 777 data
  command: "chmod 777 /home/{{ admin_user }}/server/minio/data "

- name: load minio image
  command: "docker load -i /home/{{ admin_user }}/server/minio/images/{{ ansible_architecture|lower }}/minio.tar"

- name: 配置minio服务配置文件及脚本
  template:
    src: "minio/{{ item.key }}"
    dest: "/home/{{ admin_user }}/server/minio/{{ item.value }}"
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    force: yes
    mode: 0755
  with_items:
    - { key: 'service.sh.j2' , value: 'bin/service.sh' }
    - { key: 'docker-compose.yml.j2' , value: 'bin/docker-compose.yml' }
    - { key: 'startup.sh.j2' , value: 'bin/startup.sh' }
  when: ansible_architecture|lower == "x86_64"

- name: 配置minio服务配置文件及脚本
  template:
    src: "minio/{{ item.key }}"
    dest: "/home/{{ admin_user }}/server/minio/{{ item.value }}"
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    force: yes
    mode: 0755
  with_items:
    - { key: 'service.sh.j2' , value: 'bin/service.sh' }
    - { key: 'docker-compose_aarch64.yml.j2' , value: 'bin/docker-compose.yml' }
  when: ansible_architecture|lower == "aarch64"

- name: ready to notify
  shell: ls
  notify:
    - restart minio

- name: 提前重启服务
  meta: flush_handlers