apiVersion: v1
kind: Service
metadata:
  name: app-elk-es
  namespace: app
spec:
  selector:
    app: app-elk-es
  ports:
    - name: http
      port: 9200
      targetPort: 9200
    - name: tcp
      port: 9300
      targetPort: 9300
    
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app-elk-es
  namespace: app
  labels:
    component: elk-es
    role: master
    app: app-elk-es
  annotations:
    name: app-elk-es
    company: app
    maintainer: hongchun.you@app.com
spec:
  serviceName: app-elk-es
  selector:
    matchLabels:
      app: app-elk-es
  replicas: 1
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: app-elk-es
        role: master
        app: app-elk-es
    spec:
      initContainers:
      - name: init-sysctl
        image: 10.17.148.19/app/busybox:1.35.0
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        command: ["/bin/sh"]
        args: ["-c", "sysctl -w vm.max_map_count=262144;chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: storage
          mountPath: /usr/share/elasticsearch/data
      containers:
      - name: app-elk-es
        image: 10.17.148.19/app/elk/elasticsearch:7.16.2
        resources:
          requests:
            memory: "10Gi"
            cpu: "1000m"
          limits:
            memory: "24Gi"
            cpu: "10000m"
        env:
        - name: ES_JAVA_OPTS
          value: "-Xmx8G -Xms8G"
        - name: ELASTIC_PASSWORD
          value: "123456"
        - name: discovery.type
          value: "single-node"
        - name: TZ
          value: "Asia/Shanghai"
        ports:
        - containerPort: 9300
          name: transport
        - containerPort: 9200
          name: http
        lifecycle:
          preStop:
            exec:
             command: ["/bin/ls","/tmp"]
        readinessProbe:
          tcpSocket:
            port: transport
          # exec:
          #    command: ["/bin/ls","/tmp"]
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
          failureThreshold: 3
        livenessProbe:
          tcpSocket:
            port: transport
          # exec:
          #    command: ["/bin/ls","/tmp"]
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
          failureThreshold: 3
        volumeMounts:
        - name: storage
          mountPath: /usr/share/elasticsearch/data
        - name: "elasticsearch-config"
          mountPath: "/usr/share/elasticsearch/config/elasticsearch.yml"
          subPath: "elasticsearch.yml"
      volumes:
      - name: "elasticsearch-config"                  #引用configMap卷
        configMap:    
          name: "app-ops"
          items:
            - key: "elasticsearch.yml"             #创建configMap指定的名称
              path: "elasticsearch.yml"  
  volumeClaimTemplates:
  - metadata:
      name: storage
      namespace: app
    spec:
      storageClassName: ceph-rbd
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 500Gi
